services:
  db:
    image: postgres
    container_name: it-practice-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: it_practice_db
    ports:
      - "5432:5432"
    volumes:
      - it-practice-db-data:/var/lib/postgresql

volumes:
  it-practice-db-data:
